# Generated by Django 5.0.3 on 2024-04-05 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva_turnos', '0002_consultorio_remove_turnos_profesional_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('disponible', models.BooleanField(default=True)),
                ('especialidad', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
