# Generated by Django 5.0.3 on 2024-04-19 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva_turnos', '0004_turnos_profesional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='especialidad',
            field=models.CharField(choices=[('CARDIOLOGIA', 'Cardiología'), ('DERMATOLOGIA', 'Dermatología'), ('ENDOCRINOLOGIA', 'Endocrinología'), ('GASTROENTEROLOGIA', 'Gastroenterología'), ('GINECOLOGIA', 'Ginecología'), ('HEMATOLOGIA', 'Hematología'), ('HEPATOLOGIA', 'Hepatología'), ('INMUNOLOGIA', 'Inmunología'), ('NEFROLOGIA', 'Nefrología'), ('NEUROLOGIA', 'Neurología'), ('ONCOLOGIA', 'Oncología'), ('OFTALMOLOGIA', 'Oftalmología'), ('PSICOLOGIA', 'Psicología'), ('PSIQUIATRIA', 'Psiquiatría'), ('TRAUMATOLOGIA', 'Traumatología')], default='CARDIOLOGIA', max_length=17),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='nombre_de_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
