# Generated by Django 5.0.3 on 2024-04-20 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva_turnos', '0006_alter_profesional_especialidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='especialidad',
            field=models.CharField(choices=[('CARDIOLOGIA', 'Cardiología'), ('DERMATOLOGIA', 'Dermatología'), ('ENDOCRINOLOGIA', 'Endocrinología'), ('GASTROENTEROLOGIA', 'Gastroenterología'), ('GINECOLOGIA', 'Ginecología'), ('HEMATOLOGIA', 'Hematología'), ('HEPATOLOGIA', 'Hepatología'), ('INMUNOLOGIA', 'Inmunología'), ('NEFROLOGIA', 'Nefrología'), ('NEUROLOGIA', 'Neurología'), ('ONCOLOGIA', 'Oncología'), ('OFTALMOLOGIA', 'Oftalmología'), ('PSICOLOGIA', 'Psicología'), ('PSIQUIATRIA', 'Psiquiatría'), ('TRAUMATOLOGIA', 'Traumatología')], default='CARDIOLOGIA', max_length=17),
        ),
    ]
