# Generated by Django 5.0.3 on 2024-03-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='mail',
            field=models.EmailField(max_length=50),
        ),
    ]
